#GENERAL
timeonload: true

tasks:
  '1':
    commands:
      - say This message will only show up at a specific time.
    time: '13:49'
    gender: 'console'
  '2':
    commands:
      - say This message appears every 10 seconds with a chance of 50%
    seconds: 10
    gender: 'console'
    random: 0.5